# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

        app.behat.context.transform.customer:
            class: App\Behat\Context\Transform\CustomerContext
            arguments:
                - "@sylius.repository.customer"
                - "@sylius.factory.customer"
                - "@app.behat.shared_storage"

        app.behat.context.transform.shared_storage:
            class: App\Behat\Context\Transform\SharedStorageContext
            arguments:
                - "@app.behat.shared_storage"

        app.behat.context.transform.user:
            class: App\Behat\Context\Transform\UserContext
            arguments:
                - "@app.behat.shared_storage"
