services:
    app.fixture.admin_user:
        class: App\Fixture\AdminUserFixture
        arguments:
            - "@sylius.manager.admin_user"
            - '@App\Fixture\Factory\AdminUserExampleFactory'
        tags:
            - { name: sylius_fixtures.fixture }

    app.fixture.app_user:
        class: App\Fixture\AppUserFixture
        arguments:
            - "@sylius.manager.app_user"
            - "@app.fixture.example_factory.app_user"
        tags:
            - { name: sylius_fixtures.fixture }

    app.fixture.oauth_client:
        class: App\Fixture\OAuthClientFixture
        arguments:
            - "@app.manager.oauth_client"
            - "@app.fixture.example_factory.oauth_client"
        tags:
            - { name: sylius_fixtures.fixture }
