api_platform:
    version: !php/const App\Kernel::VERSION
    mapping:
        paths:
            - '%kernel.project_dir%/src/Monofony/Pack/CorePack/.recipe/src/Entity'
            - '%kernel.project_dir%/src/Monofony/Pack/ApiPack/.recipe/config/api_platform/resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
