imports:
    - { resource: "@SyliusUserBundle/Resources/config/app/config.yml" }

security:
    encoders:
        argon2i: argon2id

sylius_user:
    resources:
        app:
            user:
                classes:
                    model: App\Entity\User\AppUser
                    repository: App\Repository\UserRepository
                    form: App\Form\Type\User\AppUserType
        admin:
            user:
                classes:
                    model: App\Entity\User\AdminUser
                    repository: Sylius\Bundle\UserBundle\Doctrine\ORM\UserRepository
                    form: App\Form\Type\User\AdminUserType
        admin_oauth:
            user:
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
                    controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
