twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        app_name_meta:
            version: !php/const App\Kernel::VERSION
    default_path:  '%kernel.project_dir%/src/Monofony/Pack/CorePack/.recipe/templates'
    paths:
        - '%kernel.project_dir%/src/Monofony/Pack/CorePack/.recipe/templates'
        - '%kernel.project_dir%/src/Monofony/Pack/AdminPack/.recipe/templates'
        - '%kernel.project_dir%/src/Monofony/Pack/FrontPack/.recipe/templates'
