sylius_grid:
    grids:
        sylius_backend_customer:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Customer\Customer
            sorting:
                createdAt: desc
            fields:
                firstName:
                    type: string
                    label: sylius.ui.first_name
                lastName:
                    type: string
                    label: sylius.ui.last_name
                email:
                    type: string
                    label: sylius.ui.email
                    sortable: true
                createdAt:
                    type: datetime
                    label: sylius.ui.registration_date
                    sortable: true
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [email, firstName, lastName]
                createdAt:
                    type: date
                    label: sylius.ui.creation_date
            actions:
                main:
                    create:
                        type: create
                item:
                    show:
                        type: show
                    update:
                        type: update
