dist: trusty

language: php

env:
    global:
        - APP_ENV=test
        - APP_NAME_CACHE_DIR=$HOME/.app_name-cache
        - APP_NAME_BUILD_DIR=etc/build

matrix:
    include:
        -
            sudo: required
            php: 7.2
            env:
                - APP_NAME_SUITE="application"
                - TRAVIS_NODE_VERSION="7.5"
            services:
                - memcached
        -
            sudo: false
            php: 7.2
            env: APP_NAME_SUITE="docs packages"
            addons:
                apt:
                    packages:
                        - parallel

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - ~/.cache/pip
        - vendor
        - node_modules
        - $APP_NAME_CACHE_DIR

before_install:
    - etc/travis/run-suite before_install "${APP_NAME_SUITE}"

install:
    - etc/travis/run-suite install "${APP_NAME_SUITE}"

before_script:
    - etc/travis/run-suite before_script "${APP_NAME_SUITE}"

script:
    - etc/travis/run-suite script "${APP_NAME_SUITE}"

before_cache:
    - etc/travis/run-suite before_cache "${APP_NAME_SUITE}"

after_success:
    - etc/travis/run-suite after_success "${APP_NAME_SUITE}"

after_failure:
    - etc/travis/run-suite after_failure "${APP_NAME_SUITE}"

after_script:
    - etc/travis/run-suite after_script "${APP_NAME_SUITE}"

notifications:
    email: false
