app_backend:
    resource: "routing/backend.yml"
    prefix: admin

app_frontend:
    resource: "routing/frontend.yml"

app_api:
    resource: "routing/api.yml"
    prefix: /api
    defaults:
        _format: json

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"