imports:
    - { resource: pages/backend.yaml }
    - { resource: pages/frontend.yaml }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

      app.behat.page:
          class: FriendsOfBehat\PageObjectExtension\Page\Page
          abstract: true
          public: false
          arguments:
              - "@behat.mink.default_session"
              - "@behat.mink.parameters"

      app.behat.symfony_page:
          class: FriendsOfBehat\PageObjectExtension\Page\SymfonyPage
          parent: app.behat.page
          abstract: true
          public: false
          arguments:
              - "@router"