imports:
    - { resource: contexts/cli.yml }
    - { resource: contexts/hook.yml }
    - { resource: contexts/setup.yml }
    - { resource: contexts/transform.yml }
    - { resource: contexts/ui.yml }
