imports:
    - { resource: pages/backend.yml }
    - { resource: pages/frontend.yml }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

      app.behat.page:
          class: App\Behat\Page\Page
          abstract: true
          public: false
          arguments:
              - "@mink.default_session"
              - "%__behat__.mink.parameters%"

      app.behat.symfony_page:
          class: App\Behat\Page\SymfonyPage
          parent: app.behat.page
          abstract: true
          public: false
          arguments:
              - "@__symfony_shared__.router"