app_backend:
    resource: "../src/Monofony/Pack/AdminPack/.recipe/config/routes/backend.yaml"

app_frontend:
    resource: "../src/Monofony/Pack/FrontPack/.recipe/config/routes/frontend.yaml"

app_api:
    resource: "../src/Monofony/Pack/ApiPack/.recipe/config/routes/api.yaml"
