parameters:
    email_contact: contact@app_name.com
    email_name: Contact AppName
    email_sender: no-reply@app_name.com

services:
    # default configuration for services in *this* file
    _defaults:
        autoconfigure: true

    command_handlers:
        namespace: App\Command\
        resource: '../src/Command/*'
        tags: [command_handler]

    sylius.controller.security:
        class: Sylius\Bundle\UiBundle\Controller\SecurityController
        public: true
        arguments:
            - "@security.authentication_utils"
            - "@form.factory"
            - "@templating.engine.twig"
            - "@security.authorization_checker"
            - "@router"

imports:
    - { resource: services/context.yml }
    - { resource: services/fixtures.yml }
    - { resource: services/fixtures_factories.yml }
    - { resource: services/form.yml }
    - { resource: services/installer.yml }
    - { resource: services/listener.yml }
    - { resource: services/menu.yml }
    - { resource: services/validator.yml }
