imports:
    - { resource: services/contexts.yaml }
    - { resource: services/pages.yaml }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.behat.admin_security:
        class: App\Behat\Service\SecurityService
        public: false
        arguments:
            - "@session"
            - "@app.behat.cookie_setter"
            - "admin"

    app.behat.app_security:
        class: App\Behat\Service\SecurityService
        public: false
        arguments:
            - "@session"
            - "@app.behat.cookie_setter"
            - "app"

    app.behat.cookie_setter:
        class: App\Behat\Service\Setter\CookieSetter
        public: false
        arguments:
            - "@behat.mink.default_session"
            - "@behat.mink.parameters"

    app.behat.current_page_resolver:
        class: App\Behat\Service\Resolver\CurrentPageResolver
        public: false
        arguments:
            - "@behat.mink.default_session"
            - "@router"

    App\Behat\Service\Resolver\CurrentPageResolverInterface:
        alias: app.behat.current_page_resolver

    app.behat.email_checker:
        class: App\Behat\Service\EmailChecker
        arguments:
            - "%kernel.cache_dir%/spool"

    App\Behat\Service\EmailCheckerInterface:
        alias: app.behat.email_checker

    app.behat.notification_accessor:
        class: App\Behat\Service\Accessor\NotificationAccessor
        public: false
        arguments:
            - "@behat.mink.default_session"

    app.behat.notification_checker:
        class: App\Behat\Service\NotificationChecker
        public: false
        arguments:
            - "@app.behat.notification_accessor"

    App\Behat\Service\NotificationCheckerInterface:
        alias: app.behat.notification_checker

    App\Behat\Service\SharedStorage:
        public: false

    App\Behat\Service\SharedStorageInterface:
        alias: App\Behat\Service\SharedStorage

    app.behat.table_accessor:
        class: App\Behat\Service\Accessor\TableAccessor
        public: false
