app_backend_dashboard:
    path: /dashboard
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'backend/index.html.twig'

sylius_backend_admin_user:
    resource: "backend/admin_user.yml"

sylius_backend_customer:
    resource: "backend/customer.yml"

sylius_backend_customer_group:
    resource: "backend/customer_group.yml"

sylius_backend_security:
    resource: "backend/security.yml"

